import { CategoryItemsTypes, ProductModel, BlogsModel } from "../types/types";
import blog1 from "../assets/blogs/blog-1.png";
import blog2 from "../assets/blogs/blog-2.png";

export const categories: CategoryItemsTypes[] = [
  {
    _id: "1",
    name: "Monitor",
    features: ["Samsung Monitors", "Asus Monitors", "LG Monitors", "Gigabyte Monitors"],
    img: "https://i.ibb.co/446nGRg/product-6.png",
  },
  {
    _id: "2",
    name: "Laptop",
    features: ["All Laptop", "Laptop accessories", "Apple Macbook", "Gaming Laptop"],
    img: "https://i.ibb.co/v3JspkB/product-7.png",
  },
  {
    _id: "3",
    name: "Gaming",
    features: ["Gaming chair", "Gaming mouse", "Gaming Keyboard ", "Gaming Headphone"],
    img: "https://i.ibb.co/St7pJJC/product-8.png",
  },
  {
    _id: "4",
    name: "Desktop",
    features: ["Brand pC", "Desktop Parts", "Apple imac", "Apple mac studio"],
    img: "https://i.ibb.co/FgqfBWj/product-11.png",
  },
  {
    _id: "5",
    name: "Tablet",
    features: ["Apple ipad", "Amazon", "Samsung", "Realme"],
    img: "https://i.ibb.co/WWMJ90v/product-10.png",
  },
  {
    _id: "6",
    name: "Accessories",
    features: ["Smart Watch", "Ear Phone", "Bluetooth Speakers", "Drones"],
    img: "https://i.ibb.co/CQgHD0f/product-9.png",
  },
];

export const categories2: CategoryItemsTypes[] = [
  {
    _id: "1",
    name: "Desktop",
    features: ["Brand pC", "Desktop Parts", "Apple imac", "Apple mac studio"],
    img: "https://i.ibb.co/wSSt8n0/computer.png",
  },
  {
    _id: "2",
    name: "Laptop",
    features: ["All Laptop", "Laptop accessories", "Apple Macbook", "Gaming Laptop"],
    img: "https://i.ibb.co/gV9sS2R/laptop.png",
  },
  {
    _id: "3",
    name: "Gadget",
    features: ["Smart Watch", "Ear Phone", "Power Bank", "Drones"],
    img: "https://i.ibb.co/xj684k9/watch.png",
  },
];

// https://i.ibb.co/Z18vrnh/product-1.png
// https://i.ibb.co/KLZNSgK/product-2.png
// https://i.ibb.co/mCSwN7D/product-3.png
// https://i.ibb.co/74KJFrn/product-4.png
// https://i.ibb.co/BLbB1Fb/product-5.png
// https://i.ibb.co/KxnRBjT/product-6.png
// https://i.ibb.co/tCJJPWx/product-7.png
// https://i.ibb.co/zHD91nv/product-8.png
// https://i.ibb.co/w0Ck9nD/product-9.png
// https://i.ibb.co/Zm5G3Lq/product-10.png
// https://i.ibb.co/HDHzRkF/product-11.png

export const productsData: ProductModel[] = [
  {
    _id: "1",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/KLZNSgK/product-2.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "2",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/HDHzRkF/product-11.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "3",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/Zm5G3Lq/product-10.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "4",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/KLZNSgK/product-2.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "5",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/tCJJPWx/product-7.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "6",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/KxnRBjT/product-6.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "7",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "8",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/74KJFrn/product-4.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/Z18vrnh/product-1.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "9",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/mCSwN7D/product-3.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "10",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/KLZNSgK/product-2.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "11",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/KLZNSgK/product-2.png",
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
  {
    _id: "12",
    name: "Apple iMac 21.5-inch Full HD Display",
    fullName:
      "Apple iMac 21.5-inch 4K Retina Display, Core i5 8th Gen, 8GB RAM, Radeon Pro 560X 4GB Graphics (MHK33ZP/A)",
    price: 30,
    regularPrice: 35,
    quantity: 3424,
    reviewQuantity: 12,
    category: "computer&Laptop",
    subCategory: "computer",
    date: "2022-12-08T13:09:29.764Z",
    status: "In Stock",
    review: 12,
    img: [
      "https://i.ibb.co/Z18vrnh/product-1.png",
      "https://i.ibb.co/KLZNSgK/product-2.png",
      "https://i.ibb.co/BLbB1Fb/product-5.png]",
      "https://i.ibb.co/BLbB1Fb/product-5.png",
    ],
    description:
      "Apple iMac (MHK33ZP/A) comes with Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz), 8GB of 2666MHz DDR4 onboard memory, 256GB SSD with Radeon Pro 560X with 4GB of VRAM Graphics. This iMac is built in 21.5 Inch (4096 x 2304) 4K Retina Display, 500 nits brightness and Wide color (P3). It has Stereo speakers, Microphone, 3.5 mm headphone jack, Bluetooth 4.2 wireless technology, Display port: Two Thunderbolt 3 (USB-C), Two Thunderbolt 3 (USB-C) ports with support for DisplayPort, Thunderbolt (up to 40 Gbps), USB 3.1 Gen 2 (up to 10 Gbps), Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately). 10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector). Kensington lock slot. This latest iMac supports macOS Sierra operating system.",
    badge: "new",
    model: "MYL324/A",
    SKU: "BE34DFDJ",
    shortFeatures: [
      'Apple iMac 21.5" Radeon Pro 560X',
      "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)",
      "8GB RAM + 256GB SSD",
      "Retina 4K 4096 x 2304 P3 display",
      "Radeon Pro 560X 4GB Graphics",
    ],
    Specification: [
      {
        ["basic Info"]: [
          { processor: "Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)" },
          { ram: "8GB 2666MHz DDR4 RAM" },
          { ["Graphics Card"]: "Radeon Pro 560X with 4GB of GDDR5 Graphics" },
          { storage: "256GB SSD" },
          {
            monitor: [
              "21.5-inch (diagonal) Retina 4K display",
              "4096-by-2304 resolution with support for one billion colors",
              "500 nits brightness",
              "Wide color (P3)",
            ],
          },
          {
            audio: ["Stereo speakers", "Microphone", "3.5 mm headphone jack"],
          },
          {
            ["Network Wireless Connectivity"]: [
              `Intel Core i5 8th Gen Processor (3.0GHz up to 4.1GHz)`,
              "LAN:",
              "10/100/1000BASE-T Gigabit Ethernet (RJ-45 connector)",
              "Wi-Fi:",
              "802.11ac Wi-Fi wireless networking",
              "IEEE 802.11a/b/g/n compatible",
              "Bluetooth:",
              "Bluetooth 4.2 wireless technology",
              "Connections and Expansion:",
              "SDXC card slot",
              "Four USB-A ports",
              "Two Thunderbolt 3 (USB-C) ports with support for:",
              "DisplayPort",
              "Thunderbolt (up to 40Gb/s)",
              "USB 3.1 Gen 2 (up to 10Gb/s)",
              "Thunderbolt 2, HDMI, DVI, and VGA supported using adapters (sold separately)",
            ],
          },
          { ["operating System"]: `macOS` },
        ],
      },
      {
        ["warranty Information"]: [{ warranty: "01 Year International Warranty" }],
      },
    ],
    updatedAt: "2022-12-08T13:09:29.764Z",
    createdAt: "2022-12-08T13:09:29.764Z",
  },
];

export const blogsData: BlogsModel[] = [
  {
    _id: "1",
    title: "What is Compliance Testing?",
    img: blog1,
    category: "development",
    tags: ["development", "Enterprise", "startups"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus ipsum vitae debitis, quam, dolore eligendi molestiae amet quasi quas quos vero odio. Ipsam commodi similique natus, corporis est dicta quae in non blanditiis velit consectetur deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    _id: "2",
    title: "What is Compliance Testing?",
    img: blog2,
    category: "development",
    tags: ["development", "Enterprise", "startups"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus ipsum vitae debitis, quam, dolore eligendi molestiae amet quasi quas quos vero odio. Ipsam commodi similique natus, corporis est dicta quae in non blanditiis velit consectetur deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    _id: "3",
    title: "What is Compliance Testing?",
    img: blog2,
    category: "development",
    tags: ["development", "Enterprise", "startups"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus ipsum vitae debitis, quam, dolore eligendi molestiae amet quasi quas quos vero odio. Ipsam commodi similique natus, corporis est dicta quae in non blanditiis velit consectetur deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },
];
