import Head from "next/head";
import Image from "next/image";
import BottomHeader1 from "../components/headers/BottomHeader1";
import MiddleHeader1 from "../components/headers/MiddleHeader1";
import TopCategories from "../components/headers/TopCategories";
import TopHeader1 from "../components/headers/TopHeader1";
import TopBannerSlider1 from "../components/sliderBanner/TopBannerSlider1";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-white min-h-screen">
        <div className="bg-secondary">
          <div className="xl:max-w-[1428px] w-full sm:mx-auto container">
            {/* ============= top header start ============== */}
            <TopHeader1 />
            <MiddleHeader1 />
            <BottomHeader1 />
            {/* ============= top header end ============== */}
          </div>
        </div>
        <div className="xl:max-w-[1428px]  mt-[30px] w-full sm:mx-auto container">
          <div className="flex gap-10">
            <TopCategories />
            <TopBannerSlider1 />
          </div>
        </div>
      </header>
      <main>
        <div>
          <h2>hello</h2>
          <button className="btn">hi</button>
        </div>
      </main>
    </>
  );
}
