import Head from "next/head";
import Image from "next/image";
import Features1 from "../components/features/Features1";
import BottomHeader1 from "../components/headers/BottomHeader1";
import MiddleHeader1 from "../components/headers/MiddleHeader1";
import TopCategories from "../components/headers/TopCategories";
import TopHeader1 from "../components/headers/TopHeader1";
import TrendingProducts from "../components/home/home1/TrendingProducts";
import TopBannerSlider1 from "../components/sliderBanner/TopBannerSlider1";

export default function Home() {
  return (
    <>
      <Head>
        <title>e-shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-white">
        <div className="bg-secondary">
          <div className="max-w-[1443px] w-full mx-auto container px-4 lg:px-10 2xl:px-0">
            {/* ============= top header start ============== */}
            <TopHeader1 />
            <MiddleHeader1 />
            <BottomHeader1 />
            {/* ============= top header end ============== */}
          </div>
        </div>
        <div className="max-w-[1443px] container lg:mt-[30px] mt-5 w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <div className="flex gap-[30px] w-full">
            <TopCategories />
            <TopBannerSlider1 />
          </div>
        </div>
      </header>
      <main className="pt-[50px]  bg-white">
        {/* ============= features start =========== */}
        <section className="max-w-[1443px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <Features1 />
        </section>
        {/* ============= features end =========== */}
        {/* ============= Trending Products start =========== */}
        <section className="max-w-[1443px] mt-20 container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <TrendingProducts />
        </section>
        {/* ============= Trending Products end =========== */}
      </main>
    </>
  );
}
