import Head from "next/head";
import React from "react";
import CardBanner2 from "../../components/Banner/CardBanner2";
import SmartBanner2 from "../../components/Banner/SmartBanner2";
import SmartBannerSlider from "../../components/Banner/SmartBannerSlider";
import TopBannerSlider2 from "../../components/Banner/TopBannerSlider2";
import TopCardBanner from "../../components/Banner/TopCardBanner";
import BottomHeader2 from "../../components/headers/BottomHeader2";
import MiddleHeader1 from "../../components/headers/MiddleHeader1";
import TopCategories from "../../components/headers/TopCategories";
import TopHeader2 from "../../components/headers/TopHeader2";
import FeaturedProducts2 from "../../components/home/home2/FeaturedProducts2";
import HotNewArrivals from "../../components/home/home2/HotNewArrivals";
import OnSaleProducts from "../../components/home/home2/OnSaleProducts";
import SpecialProducts2 from "../../components/home/home2/SpecialProducts2";
import TopTrendingRecentlyGroupSec from "../../components/home/home2/TopTrendingRecentlyGroupSec";
import TrendingCategories from "../../components/home/home2/TrendingCategories";
import ShopByCategories from "../../components/home/home2/ShopByCategories";
import Footer2 from "../../components/shared/footer/Footer2";
import ScrollUpBtn from "../../components/shared/ScrollUpBtn";

const Home2 = () => {
  return (
    <>
      <Head>
        <title>e-shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        {/* ============= top header start ============== */}
        <TopHeader2 />
        <MiddleHeader1 />
        <BottomHeader2 />
        {/* ============= top header end ============== */}

        <div className="max-w-[1443px] container lg:mt-[30px] mt-5 w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <div className="flex gap-[30px] w-full">
            <TopCategories />
            <TopBannerSlider2 />
            <TopCardBanner />
          </div>
        </div>
      </header>
      <main>
        {/*======== single product banner section start ============*/}
        <section className="max-w-[1443px] container pt-10 lg:pt-[60px] w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <ShopByCategories />
        </section>
        {/*======== single product banner section end ==============*/}
        {/* ============= Trending Products start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <HotNewArrivals />
        </section>
        {/* ============= Trending Products end =========== */}
        {/* ============= Special Products start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <SpecialProducts2 />
        </section>
        {/* ============= Special Products end =========== */}
        {/* ============= Trending Categories start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <TrendingCategories />
        </section>
        {/* ============= Trending Categories end =========== */}
        {/* ============= smart banner start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <SmartBannerSlider />
        </section>
        {/* ============= smart banner end =========== */}
        {/* ============= On Sale Products start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <OnSaleProducts />
        </section>
        {/* ============= On Sale Products end =========== */}
        {/* ============= card banner start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <CardBanner2 />
        </section>
        {/* ============= Top Trending Recently Group Sec start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <TopTrendingRecentlyGroupSec />
        </section>
        {/* ============= Top Trending Recently Group Sec end =========== */}
        {/* ============= smart banner start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <SmartBanner2 />
        </section>
        {/* ============= smart banner end =========== */}
        {/* ============= Featured Products start =========== */}
        <section className="max-w-[1443px] mt-20 lg:mt-[120px] container w-full mx-auto px-4 lg:px-10 2xl:px-0">
          <FeaturedProducts2 />
        </section>
        {/* ============= Featured Products end =========== */}
        {/* ======== scroll up button start ======= */}
        <ScrollUpBtn />
        {/* ======== scroll up button end ======= */}
      </main>
      <footer className="mt-[146px] lg:mt-[186px] ">
        <Footer2 />
      </footer>
    </>
  );
};

export default Home2;
